site_name: Notes Not Scandal
site_url: https://didiowen.github.io/notes-not-scandal/
site_description: inspired by Cate Blanchett's Notes on a Scandal
site_author: YW Chen

theme:
    name: 'material'
    features:
        - navigation.path
        - navigation.tabs
        - navigation.tabs.sticky
        - navigation.sections
        - navigation.tracking
        - navigation.top
        - toc.follow
        - search.highlight

    palette:

    # Light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: lime
      accent: teal
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode

    # Dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: teal
      accent: lime
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode

# Extensions
markdown_extensions:
  - footnotes
  - md_in_html
  - abbr # adds the ability to add a small tooltip to an element, by wrapping it with an abbr tag
  - admonition # adds support for admonitions, more commonly known as call-outs, which can be defined in Markdown
  - attr_list # allows to add HTML attributes and CSS classes to almost every Markdown inline- and block-level element with a special syntax
  - pymdownx.arithmatex: # allows for rendering of block and inline block equations and integrates seamlessly with MathJax
      generic: true
  - tables
  - toc:
      permalink: true
      title: Table of contents
  - pymdownx.tasklist:
      custom_checkbox: true
  - def_list
  - nl2br
  - pymdownx.critic # allows for the usage of Critic Markup to highlight added, deleted or updated sections in a document
  - pymdownx.caret # The Caret, Mark and Tilde extensions add the ability to highlight text and define sub- and superscript using a simple syntax
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.keys # adds a simple syntax to allow for the rendering of keyboard keys and combinations
  - pymdownx.betterem # improves the detection of Markup to emphasize text in Markdown using special characters
  - pymdownx.details # supercharges the Admonition extension, making the resulting call-outs collapsible
  - pymdownx.superfences # allows for arbitrary nesting of code and content blocks inside each other, including admonitions, tabs, lists and all other elements
  - pymdownx.magiclink
#  - pymdownx.superfences:
#      custom_fences:
#        - name: mermaid
#          class: mermaid
#          format: !!python/name:pymdownx.superfences.fence_code_format


plugins:
  - search
  - callouts
  - roamlinks
  - blog:
      blog_dir: .
      blog_toc: true
      pagination: false
      pagination_per_page: 3
      post_excerpt_separator: <!-- more -->
      post_url_format: "{categories}/{slug}"
      post_url_max_categories: 1
      post_slugify: !!python/object/apply:pymdownx.slugs.slugify
        kwds:
          case: lower
      archive_date_format: yyyy/MM
      archive_url_date_format: yyyy/MM
  - git-revision-date-localized:
      type: timeago
#  - bibtex:
#      bib_file: "docs/assets/library.bib"
#      bib_by_default: true
#      csl_file: "docs/assets/harvard-imperial.csl"
#      cite_inline: true
#  - minify:
#      minify_html: true
#      minify_js: true
#      minify_css: true
#  - glightbox
#extra:
#  SEO: assets/meta/SEO.png
#  comments: $comments #disable comments globally
#  generate_graph: $generate_graph #generate the graph of the site
#  no-auto-h1: $auto_h1 #disable the automatic generation of h1 if no h1 is found
#  blog_list:
#    pagination: true #enable pagination
#    pagination_message: true #display the message "Showing x posts out of y"
#    pagination_translation: 'posts in' #message to display before the number of posts ; Add your own translation!
#    no_page_found: "No pages found!" #message to display when no pages are found ; Add your own translation!
#hooks:
#  - overrides/hooks/on_page_markdown.py
#  - overrides/hooks/on_env.py
#  - overrides/hooks/on_files.py
#hooks:
#    strip_comments: true
#    fix_heading: true

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
#  - https://unpkg.com/mermaid/dist/mermaid.min.js 
  - https://cdn.jsdelivr.net/gh/ObsidianPublisher/assets@main/dist/javascript.js
extra_css:
    - https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css
