site_name: Notes Not Scandal
site_url: https://didiowen.github.io/notes-not-scandal/
site_author: YW Chen

theme:
    name: 'material'
    features:
        - navigation.path
    palette:

    # Light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: pink
      accent: indigo
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode

    # Dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: pink
      accent: blue
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode

# Extensions
markdown_extensions:
  - footnotes
  # - attr_list
  - pymdownx.arithmatex:
      generic: true
  # - pymdownx.superfences
  # - pymdownx.details
  # - pymdownx.magiclink
  - pymdownx.tasklist:
      custom_checkbox: true
  - def_list
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - tables

  - toc:
      permalink: true
      title: On this page

plugins:
  - search
  - roamlinks
#- bibtex:
#      bib_file: "refs.bib"
#hooks:
#  - overrides/hooks/on_page_markdown.py
#  - overrides/hooks/on_env.py
#  - overrides/hooks/on_files.py
#extra:
#  SEO: assets/meta/SEO.png
#  comments: $comments #disable comments globally
#  generate_graph: $generate_graph #generate the graph of the site
#  no-auto-h1: $auto_h1 #disable the automatic generation of h1 if no h1 is found
#  blog_list:
#    pagination: true #enable pagination
#    pagination_message: true #display the message "Showing x posts out of y"
#    pagination_translation: 'posts in' #message to display before the number of posts ; Add your own translation!
#    no_page_found: "No pages found!" #message to display when no pages are found ; Add your own translation!
#hooks:
#    strip_comments: true
#    fix_heading: true

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
  - https://unpkg.com/mermaid/dist/mermaid.min.js 
